
###########################################################
# GENERATED FILE. DO NOT EDIT
# Generated by stackato-ops/dev-tools/gemlocker/gemlocker
###########################################################

source (ENV['RUBYGEMS_MIRROR'] or 'https://rubygems.org')

ruby '1.9.3' # prevents hard-to-diagnose errors with bundle install

gem 'activemodel'       ,   '3.2.18'
gem 'activerecord'      ,   '3.2.18', :require => 'active_record'
gem 'activesupport'     ,   '3.2.18'
gem 'addressable'       ,    '2.3.5'
gem 'arel'              ,    '3.0.3'
gem 'attr_required'     ,    '0.0.5'
gem 'axiom-types'       ,    '0.0.5'
gem 'bcrypt-ruby'       ,    '3.0.1', :require => 'bcrypt'
gem 'builder'           ,    '3.0.4'
gem 'cf-message-bus'    ,    '0.0.5', :git => "https://github.com/ActiveState/cf-message-bus.git", :ref => "dbc2fc6e"
gem 'cf-uaa-lib'        ,    '1.3.7', :git => "https://github.com/cloudfoundry/cf-uaa-lib.git", :ref => "8d34eede"
gem 'ci_reporter'       , :groups => [:test]
gem 'coercible'         ,    '1.0.0'
gem 'colored'           ,      '1.2'
gem 'cookiejar'         ,    '0.3.0'
gem 'daemons'           ,    '1.1.9'
gem 'descendants_tracker',    '0.0.3'
gem 'diff-lcs'          ,    '1.2.5'
gem 'docopt'            ,    '0.5.0'
gem 'em-http-request'   ,    '1.1.2'
gem 'em-socksify'       ,    '0.3.0'
gem 'equalizer'         ,    '0.0.9'
gem 'eventmachine'      ,    '1.0.3'
gem 'ffi'               ,    '1.9.3', :groups => [:development]
gem 'fluent-logger'     ,    '0.4.7'
gem 'grape'             ,    '0.6.1'
gem 'hashie'            ,    '2.0.5'
gem 'http_parser.rb'    ,    '0.6.0'
gem 'httpclient'        ,  '2.3.4.1'
gem 'i18n'              ,    '0.6.9'
gem 'ice_nine'          ,   '0.11.0'
gem 'ipaddress'         ,    '0.8.0'
gem 'json'              ,    '1.8.1'
gem 'json_pure'         ,    '1.8.1'
gem 'listen'            ,    '1.0.3', :groups => [:development]
gem 'membrane'          ,    '0.0.2'
gem 'mime-types'        ,      '2.0'
gem 'mini_portile'      ,    '0.5.2'
gem 'msgpack'           ,    '0.5.8'
gem 'multi_json'        ,    '1.8.4'
gem 'multi_xml'         ,    '0.5.5'
gem 'multipart-post'    ,    '2.0.0'
gem 'mustache'          ,   '0.99.4'
gem 'nats'              ,   '0.4.26'
gem 'net-ldap'          ,    '0.6.1'
gem 'nokogiri'          ,    '1.6.1'
gem 'omniauth'          ,    '1.1.4'
gem 'omniauth-google-apps',    '0.0.2'
gem 'omniauth-identity' ,    '1.1.1'
gem 'omniauth-ldap'     ,    '1.0.4', :github => 'ActiveState/omniauth-ldap'
gem 'omniauth-openid'   ,    '1.0.1'
gem 'parallel_tests'    , :groups => [:test]
gem 'pg'                ,   '0.14.1'
gem 'posix-spawn'       ,    '0.3.8'
gem 'pyu-ruby-sasl'     ,  '0.0.3.3'
gem 'rack'              ,    '1.5.2', :groups => [:default, :test]
gem 'rack-accept'       ,    '0.4.5'
gem 'rack-mount'        ,    '0.8.3'
gem 'rack-oauth2'       ,    '1.0.7'
gem 'rack-openid'       ,    '1.3.1'
gem 'rack-protection'   ,    '1.5.1'
gem 'rack-test'         ,    '0.6.2', :groups => [:test]
gem 'rake'              ,   '10.1.1'
gem 'rb-fsevent'        ,    '0.9.4', :groups => [:development]
gem 'rb-inotify'        ,    '0.9.3', :groups => [:development]
gem 'rb-kqueue'         ,    '0.2.0', :groups => [:development]
gem 'redis'             ,    '3.0.6'
gem 'rerun'             ,    '0.8.2', :groups => [:development]
gem 'rspec'             ,   '2.14.1'
gem 'rspec-core'        ,   '2.14.7'
gem 'rspec-expectations',   '2.14.4'
gem 'rspec-mocks'       ,   '2.14.4'
gem 'ruby-openid'       ,    '2.3.0'
gem 'ruby-openid-apps-discovery',    '1.2.0'
gem 'ruby-termios'      ,    '0.9.6'
gem 'rubyntlm'          ,    '0.1.1'
gem 'scim-query-filter-parser',    '0.0.4', :require => 'scim/query/filter/parser'
gem 'simplecov'         , :groups => [:test]
gem 'simplecov-rcov'    , :groups => [:test]
gem 'sinatra'           ,    '1.3.6', :require => 'sinatra/base'
gem 'sqlite3'           ,    '1.3.7'
gem 'squash_ruby'       ,    '1.4.0'
gem 'stackato-kato'     ,    '3.0.0'
gem 'steno'             ,    '1.2.2'
gem 'term-ansicolor'    ,    '1.0.7'
gem 'thin'              ,    '1.6.1'
gem 'tilt'              ,    '1.4.1'
gem 'tzinfo'            ,   '0.3.38'
gem 'vcap-concurrency'  ,    '0.1.0'
gem 'vcap_common'       ,    '2.2.0', :require => ['cf/registrar','vcap/common','vcap/component', 'json_message'], :git => "https://github.com/ActiveState/vcap-common.git", :ref => "abd9790e"
gem 'virtus'            ,    '1.0.1'
gem 'vmstat'            ,    '2.1.0'
gem 'webmock'           , :groups => [:test]
gem 'xmlparser'         ,  '0.7.2.1'
gem 'yajl-ruby'         ,    '1.1.0'
gem 'zxcvbn-ruby'       ,    '0.0.2', :require => 'zxcvbn'

